### ISSUE TITLE
Fix message/event HTTP sending

### ISSUE THREAD

**Issue by rudigiesler** [praekelt/junebug#121]
Sometimes the processing of messages/events gets stuck. I'm using this ticket to track all the errors that I see when this happens, so that we can look into catching them properly.

```
2017-04-19 09:20:57,934 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
Failure: twisted.web._newclient.RequestTransmissionFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>]

2017-04-19 09:20:57,934 [twisted] CRITICAL: Unexpected exception from twisted.web.client.FileBodyProducer.stopProducing
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 130, in connectionLost
    return self._wrappedProtocol.connectionLost(reason)
  File "/usr/local/lib/python2.7/site-packages/twisted/web/_newclient.py", line 929, in dispatcher
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/twisted/web/_newclient.py", line 1599, in _connectionLost_TRANSMITTING
    self._currentRequest.stopWriting()
  File "/usr/local/lib/python2.7/site-packages/twisted/web/_newclient.py", line 830, in stopWriting
    _callAppFunction(self.bodyProducer.stopProducing)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/web/_newclient.py", line 194, in _callAppFunction
    function()
  File "/usr/local/lib/python2.7/site-packages/twisted/web/client.py", line 1041, in stopProducing
    self._task.stop()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/task.py", line 497, in stop
    self._checkFinish()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/task.py", line 507, in _checkFinish
    raise self._completionState
twisted.internet.task.TaskStopped: 
```

```2017-04-26 07:15:52,572 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
Failure: twisted.web._newclient.RequestTransmissionFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>]

2017-04-26 07:15:52,573 [twisted] CRITICAL: Unexpected exception from twisted.web.client.FileBodyProducer.stopProducing
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 130, in connectionLost
    return self._wrappedProtocol.connectionLost(reason)
  File "/usr/local/lib/python2.7/site-packages/twisted/web/_newclient.py", line 929, in dispatcher
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/twisted/web/_newclient.py", line 1599, in _connectionLost_TRANSMITTING
    self._currentRequest.stopWriting()
  File "/usr/local/lib/python2.7/site-packages/twisted/web/_newclient.py", line 830, in stopWriting
    _callAppFunction(self.bodyProducer.stopProducing)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/web/_newclient.py", line 194, in _callAppFunction
    function()
  File "/usr/local/lib/python2.7/site-packages/twisted/web/client.py", line 1041, in stopProducing
    self._task.stop()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/task.py", line 497, in stop
    self._checkFinish()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/task.py", line 507, in _checkFinish
    raise self._completionState
twisted.internet.task.TaskStopped: ```

**Comment by rudigiesler** [comment]
This seems to have been fixed by https://github.com/praekelt/junebug/pull/137
